name: Android CI

on:
  push:
    branches: [ feature/bluetooth-controller-support, master, main ]
  pull_request:
    branches: [ feature/bluetooth-controller-support, master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew

    - name: Build with Gradle
      run: |
        cd android
        ./gradlew assembleDebug --no-daemon

    - name: Run tests
      run: |
        cd android
        ./gradlew test --no-daemon

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
